"""
Test Case Generator Agent.

Takes a Jira-style ticket and produces a numbered list of test cases
(positive + negative) using a tool-using agent loop.

The agent has two tools:
- extract_criteria: parse the ticket into individual acceptance criteria
- validate_coverage: check whether generated tests cover each criterion

The agent typically follows this sequence:
1. Call extract_criteria to get a clean list of ACs
2. Reason about positive and negative test cases for each AC
3. Call validate_coverage to check its own work
4. If gaps, generate additional test cases
5. Return the final test case list
"""

from anthropic import Anthropic
from dotenv import load_dotenv

from tools import TOOL_SCHEMAS, execute_tool
from sample_ticket import SAMPLE_TICKET


load_dotenv()
client = Anthropic()


# ============================================================
# The system prompt that defines the agent's role
# ============================================================

SYSTEM_PROMPT = """You are a senior QA engineer with deep experience writing test cases for software features. You write clear, actionable test cases that a manual tester could execute without ambiguity.

When given a Jira-style ticket, your job is to:

1. FIRST, call the extract_criteria tool to identify each acceptance criterion separately. Do not try to parse the ticket yourself.

2. For each criterion, design POSITIVE test cases (happy path - the feature works as intended) AND NEGATIVE test cases (invalid input, error conditions, security boundaries).

3. After drafting your test cases, call the validate_coverage tool to check whether every criterion is covered by at least one test case.

4. If validate_coverage reports any missing criteria, generate additional test cases for those criteria and stop only when coverage is satisfactory.

5. Return the final test cases in this exact format:

   TEST CASES
   ==========

   1. [POSITIVE] <Short title>
      Steps:
        1. <step>
        2. <step>
      Expected: <clear expected outcome>

   2. [NEGATIVE] <Short title>
      Steps:
        1. <step>
        2. <step>
      Expected: <clear expected outcome>

   ...and so on.

Aim for a roughly even mix of positive and negative cases. Each test case must be specific, executable by a human tester, and tied to one or more acceptance criteria. Do not include test cases for things outside the acceptance criteria."""


# ============================================================
# The agent loop
# ============================================================

def generate_test_cases(ticket_text: str, model: str = "claude-opus-4-7",
                        max_iterations: int = 10, verbose: bool = True) -> str:
    """
    Runs the full agent loop for a single ticket.

    Returns the final test case text generated by the agent.
    Set verbose=False to suppress step-by-step output.
    """
    messages = [
        {
            "role": "user",
            "content": f"Generate test cases for this ticket:\n\n{ticket_text}"
        }
    ]

    final_text = ""

    for iteration in range(1, max_iterations + 1):
        if verbose:
            print(f"\n--- Agent iteration {iteration} ---")

        response = client.messages.create(
            model=model,
            max_tokens=4096,
            system=SYSTEM_PROMPT,
            tools=TOOL_SCHEMAS,
            messages=messages
        )

        # Show what Claude returned this iteration
        tool_uses_this_turn = []
        for block in response.content:
            if block.type == "text":
                if verbose and block.text.strip():
                    print(f"[Claude says]: {block.text[:200]}...")
                final_text = block.text  # keep the most recent text
            elif block.type == "tool_use":
                if verbose:
                    print(f"[Claude calls tool]: {block.name}")
                tool_uses_this_turn.append(block)

        # If Claude is done (no more tool calls), we exit the loop
        if response.stop_reason != "tool_use":
            if verbose:
                print(f"\n[Agent finished after {iteration} iteration(s)]")
            break

        # Otherwise, run the tools and feed results back
        messages.append({"role": "assistant", "content": response.content})

        tool_results = []
        for tool_block in tool_uses_this_turn:
            result = execute_tool(tool_block.name, tool_block.input)
            if verbose:
                # Show a short preview of the tool result
                result_preview = str(result)[:150]
                print(f"[Tool result]: {result_preview}...")
            tool_results.append({
                "type": "tool_result",
                "tool_use_id": tool_block.id,
                "content": str(result)
            })

        messages.append({"role": "user", "content": tool_results})

    return final_text


# ============================================================
# Run the agent on our sample ticket
# ============================================================

if __name__ == "__main__":
    import sys
    from sample_ticket import SAMPLE_TICKET, SAMPLE_TICKET_2

    # Let user pick a ticket from the command line: python agent.py 1 or 2
    ticket_choice = sys.argv[1] if len(sys.argv) > 1 else "1"
    ticket = SAMPLE_TICKET if ticket_choice == "1" else SAMPLE_TICKET_2

    print("=" * 70)
    print(f"TEST CASE GENERATOR AGENT  (ticket #{ticket_choice})")
    print("=" * 70)
    print("\nInput ticket:")
    print("-" * 70)
    print(ticket[:300] + "...\n")
    print("=" * 70)
    print("Running agent...")
    print("=" * 70)

    raw_output = generate_test_cases(ticket, verbose=True)

    # Strip preamble: find where the actual test cases begin
    # We look for "TEST CASES" or the first numbered item ("1. [")
    cleaned = raw_output
    for marker in ["TEST CASES", "1. [POSITIVE", "1. [NEGATIVE"]:
        idx = raw_output.find(marker)
        if idx != -1:
            cleaned = raw_output[idx:]
            break

    print("\n" + "=" * 70)
    print("FINAL TEST CASES")
    print("=" * 70)
    print(cleaned)

    # Also save to a file for easy sharing
    output_filename = f"test_cases_ticket_{ticket_choice}.md"
    with open(output_filename, "w", encoding="utf-8") as f:
        f.write(f"# Test Cases for Ticket #{ticket_choice}\n\n")
        f.write(cleaned)
    print(f"\n[Saved to {output_filename}]")